PowerBank/PowerBank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

PowerBank/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'main'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('remit/', views.remit, name='remit'),
    path('balance/', views.balance, name='balance'),
    path('log/', views.log, name='log'),
    path('gmoney/', views.gmoney, name='gmoney'),
]

PowerBank/main/models.py
from django.db import models
from django.contrib.auth.models import User
    
class Bak(models.Model):
    CHOICES = (
        ('NN', 'none'),
	    ('HB', 'hangbu'),
        ('HBM', 'hangbumem'),
        ('IB', 'ibbu'),
        ('IBM', 'ibbumem'),
        ('GB', 'gambu'),
        ('GBM', 'gambumem'),
  )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    money = models.IntegerField(default='400')
    work = models.CharField(max_length=3, choices=CHOICES, null=True)

    def __str__(self):
        return self.user.username

# Create your models here.

PowerBank/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import check_password
from django.contrib import auth
from django.contrib.auth.models import User
from .models import Bak
import logging
import logging.handlers


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s %(message)s')



def start_log(request):
    filehandler = logging.FileHandler(f'./logs/logfile_{request}.log', encoding='utf-8')
    filehandler.setFormatter(formatter)
    logger.addHandler(filehandler)

    return filehandler

def stop_log(filehandler):
    logger.removeHandler(filehandler)

def change_pw(request):
    context= {}
    if request.method == "POST":
        current_password = request.POST.get("origin_password")
        user = request.user
        if check_password(current_password,user.password):
            new_password = request.POST.get("password1")
            password_confirm = request.POST.get("password2")
            if new_password == password_confirm:
                user.set_password(new_password)
                user.save()
                auth.login(request,user)
                return redirect("main:login")
            else:
                context.update({'error':"새로운 비밀번호를 다시 확인해주세요."})
        context.update({'error':"현재 비밀번호가 일치하지 않습니다."})

    return render(request, "main/change_pw.html",context)

def remit(request):
    context= {}
    if request.method == "POST":
        current_password = request.POST.get("password")
        user = request.user
        puser = request.POST.get("pname")
        if int(request.POST.get("bak")) > 0:
            if check_password(current_password,user.password):
                for pname in User.objects.values('username'):
                    if "%s"%pname in "{'username': '%s'}"%puser:
                        gmoney = Bak.objects.get(user=user)
                        
                        pid = str(User.objects.filter(username=puser).values('id'))[18:20]
                        if "}" in pid:
                            pid = pid[0:1]
                        pmoney = Bak.objects.get(user=int(pid))

                        if gmoney.money < int(request.POST.get("bak")):
                            context.update({'error':"잔고가 부족합니다."})
                        else:
                            if str(User.get_username(user)) == str(puser):
                                context.update({'error':"본인에게 송금은 불가합니다."})
                            else:
                                gmoney.money = gmoney.money - int(request.POST.get("bak"))
                                pmoney.money = pmoney.money + int(request.POST.get("bak"))
                                gmoney.save()
                                pmoney.save()
                                a = start_log('goverment')
                                b = start_log(puser)
                                c = start_log(User.get_username(user))
                                logger.info(User.get_username(user)+ " 송금 " +  request.POST.get("bak") + "박 " + puser)
                                context.update({'error':"정상적으로 처리되었습니다."})
                                stop_log(a)
                                stop_log(b)
                                stop_log(c)
                        return render(request, "main/remit.html",context)
                    
                context.update({'error':"받는 사람 이름을 다시 확인해주세요."})
            else:
                context.update({'error':"비밀번호가 일치하지 않습니다."})
        else:
            context.update({'error':"금액은 자연수로 입력해주세요"})

    return render(request, "main/remit.html",context)

def balance(request):
    context= {}
    
    user = request.user

    testFile = open(f'./logs/logfile_{User.get_username(user)}.log','rt',encoding="utf8")

    gmoney = Bak.objects.get(user=user)


    logs = testFile.readlines()
    context.update({'logs':logs})
    context.update({'balance':gmoney.money})
    testFile.close()
                        
    return render(request, "main/balance.html",context)

def log(request):
    context= {}

    testFile = open('./logs/logfile_goverment.log','rt',encoding="utf8")

    logs = testFile.readlines()
    context.update({'logs':logs})

    testFile.close()
                        
    return render(request, "main/log.html",context)

def gmoney(request):
    context= {}
    if request.method == "POST":
        puser = request.POST.get("pname")
        if int(request.POST.get("bak")) > 0:
            
            for pname in User.objects.values('username'):
                if "%s"%pname in "{'username': '%s'}"%puser:
                    
                    
                    pid = str(User.objects.filter(username=puser).values('id'))[18:20]
                    if "}" in pid:
                            pid = pid[0:1]
                    pmoney = Bak.objects.get(user=int(pid))
                    a = start_log('goverment')
                    b = start_log(puser)
                    if str(request.POST.get("gtype")) == "sang":
                        pmoney.money = pmoney.money + int(request.POST.get("bak"))
                        logger.info("정부 상금 " +  request.POST.get("bak") + "박 " + puser + " 사유: " + str(request.POST.get("why")))
                    else:
                        pmoney.money = pmoney.money - int(request.POST.get("bak"))
                        logger.info("정부 벌금 " +  request.POST.get("bak") + "박 " + puser + " 사유: " + str(request.POST.get("why")))
                    stop_log(a)
                    stop_log(b)
                    pmoney.save()
                    
                    context.update({'error':"정상적으로 처리되었습니다."})
                    return render(request, "main/gmoney.html",context)
                
            context.update({'error':"받는 사람 이름을 다시 확인해주세요."})
        else:
            context.update({'error':"금액은 자연수로 입력해주세요"})

    return render(request, "main/gmoney.html",context)


# Create your views here.

PowerBank/main/templates/main/balance.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>파워뱅크</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 80px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
    </style>
</head>
<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }}님 (로그아웃)</a>
    <a class="nav-link b" href="{% url 'main:login' %}">홈으로</a>
    <a class="nav-link b" href="{% url 'main:change_pw' %}">(비밀번호 변경)</a>
    <div class="power">
        <h1>현재 잔고: {{balance}}박</h1>
        {% for log in logs %}
            {{log}}<br>
        {% endfor %}
    </div>
</body>

PowerBank/main/templates/main/change_pw.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 60px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
        strong {
            font-size: 25px;
            color: firebrick;
        }
</style>
<div class="container">
    <div class="login_container">
        <a class="nav-link b" href="{% url 'main:login' %}">홈으로</a>
                
        <div class="login_title">
            <h1>비밀번호 변경</h1>
        </div>
        <div class="error_message">
            <strong>{{error}}</strong>
        </div>
        <form method="POST" action="{% url 'main:change_pw' %}" class="login_form">
            {% csrf_token %}

            <div class="login_input_container">
                <div class="username_form_text">현재 비밀번호</div>
                <div class="input_container">
                    <input class="login_input" name="origin_password" type="password">
                </div>

                <div class="password_form_text"> 새로운 비밀번호</div>
                <div class="input_container">
                    <input class="login_input" name="password1" type="password">
                </div>
                <div class="confirm_password_form_text">비밀번호 재입력</div>
                <div class="input_container">
                    <input class="login_input" name="password2" type="password">
                </div>
            </div>
            <div class="login_btn_container">
                <input type="submit" class="login_btn" value="확인">
            </div>
    </div>
    </form>
</div>

PowerBank/main/templates/main/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

PowerBank/main/templates/main/gmoney.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>파워뱅크</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 60px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
        p {
            font-size: 30px;
        }
        .h {
            font-size: 20px;
        }
    </style>
</head>
{% if user.is_authenticated %}
<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }} (로그아웃)</a>
    <a class="nav-link b" href="{% url 'main:login' %}">홈으로</a>
    <a class="nav-link b" href="{% url 'main:change_pw' %}">(비밀번호 변경)</a>
    <form method="post" action="{% url 'main:gmoney' %}">
        {% if user.is_staff %}
        {% csrf_token %}
        {{error}}
        <div class="mb-3">
            <label for="pname">대상인</label>
            <input type="text" class="form-control" name="pname" id="pname"
                   value="{{ form.pname.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="bak">금액</label>
            <input type="number" class="form-control" name="bak" id="bak"
                   value="{{ form.bak.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="why">사유</label>
            <input required type="text" class="form-control" name="why" id="why"
                   value="{{ form.pname.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <p>상/벌금</p>
            <label class="h"><input type="radio" class="form-control" name="gtype" id="gtype" value="sang">상금</label>
            <label class="h"><input type="radio" class="form-control" name="gtype" id="gtype" value="beul">벌금</label>
        </div>
        <button type="submit" class="btn btn-primary power">책정</button>
    </form>
    {% endif %}
</body>
{% endif %}
</html>

PowerBank/main/templates/main/log.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>파워뱅크</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 80px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
    </style>
</head>

<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }}님 (로그아웃)</a>
    <a class="nav-link b" href="{% url 'main:login' %}">홈으로</a>
    <a class="nav-link b" href="{% url 'main:change_pw' %}">(비밀번호 변경)</a>
    
    <div class="power">
    {% if user.is_staff %}
        {% for log in logs %}
            {{log}}<br>
        {% endfor %}
    {% else %}
    <h1 style="color: darkred;">잘못된 접근</h1>
    {% endif %}
    </div>
</body>

PowerBank/main/templates/main/login.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>파워뱅크</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 60px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
    </style>
</head>
{% if user.is_authenticated %}
{% if user.is_staff %}
<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }} (로그아웃)</a>
    <div class="power">
        <a href=""><button type="button" class="btn btn-primary a">공무원관리<br>(coming soon)</button></a>
        <a href="{% url 'main:gmoney' %}"><button type="button" class="btn btn-secondary a">상벌금</button></a>
        <a href="{% url 'main:log' %}"><button type="button" class="btn btn-success a">재정로그</button></a>
    </div>
</body>
{% else %}
<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }}님 (로그아웃)</a>
    <a class="nav-link b" href="{% url 'main:change_pw' %}">(비밀번호 변경)</a>
    <div class="power">
    <a href="{% url 'main:remit' %}"><button type="button" class="btn btn-primary a">송금</button></a>
    <a href=""><button type="button" class="btn btn-secondary a">구매<br>(coming soon)</button></a>
    <a href="{% url 'main:balance' %}"><button type="button" class="btn btn-success a">잔고</button></a>
    </div>
</body>
{% endif %}
{% else %}
<body>
    <div class="power">
        <img src="{% static 'bank.png' %}" alt="My Image" height="100">
        <h1>파워뱅크</h1>
    </div>
    
    <div class="container my-3" style="width: 100%;">
        <form method="post" action="{% url 'main:login' %}">
            {% csrf_token %}
            {% include "./form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자 이름</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary power">로그인</button>
        </form>
    </div>
</body>
{% endif %}
</html>

PowerBank/main/templates/main/remit.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>파워뱅크</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <style>
        * {
            font-family: 'Black Han Sans', sans-serif;
            font-weight: 100;
            font-size: 20px;
        }
        h1 {
            font-size: 60px;
            
        }
        .power {
            text-align: center;
        }
        .a {
            font-family: 'Black Han Sans', sans-serif;
            font-size: 40px;
            width: 30%;
            height: 600px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            margin-left: 10px;
            margin-right: 10px;
        }
        .b {
            font-size: 30px;
        }
        html,
        body {
        width: 100vw;
        height: 100vh;
        }
        label {
            font-size: 30px;
        }
    </style>
</head>
{% if user.is_authenticated %}
<body>
    <a class="nav-link b" href="{% url 'main:logout' %}">{{ user.username }}님 (로그아웃)</a>
    <a class="nav-link b" href="{% url 'main:login' %}">홈으로</a>
    <a class="nav-link b" href="{% url 'main:change_pw' %}">(비밀번호 변경)</a>
    <form method="post" action="{% url 'main:remit' %}">
        {% csrf_token %}
        {{error}}
        <div class="mb-3">
            <label for="pname">받는사람</label>
            <input type="text" class="form-control" name="pname" id="pname"
                   value="{{ form.pname.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="bak">금액</label>
            <input type="number" class="form-control" name="bak" id="bak"
                   value="{{ form.bak.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary power">송금</button>
    </form>
</body>
{% endif %}
</html>